/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4NtEGLh5Av4kRFEg1oTSHSpPbN-vRnpI',
    appId: '1:787602166813:web:b08e718f604328de9c22f4',
    messagingSenderId: '787602166813',
    projectId: 'dtchecker-6e966',
    authDomain: 'dtchecker-6e966.firebaseapp.com',
    storageBucket: 'dtchecker-6e966.appspot.com',
    measurementId: 'G-0VB9MLFJPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoL9PLWkhaB7c5p5rOr_LYb0FDuK_ZGRE',
    appId: '1:787602166813:android:99c394882d0cbc049c22f4',
    messagingSenderId: '787602166813',
    projectId: 'dtchecker-6e966',
    storageBucket: 'dtchecker-6e966.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi0hN1Oz5iYtnZYrndc0cjnsiV20GRE_U',
    appId: '1:787602166813:ios:f8334a1cb63d9e649c22f4',
    messagingSenderId: '787602166813',
    projectId: 'dtchecker-6e966',
    storageBucket: 'dtchecker-6e966.appspot.com',
    androidClientId: '787602166813-07oq9t6hst61v426gdorak2hao2976gm.apps.googleusercontent.com',
    iosClientId: '787602166813-raoj9gpt4tp6lgf6a10kijo53dh9hjk3.apps.googleusercontent.com',
    iosBundleId: 'com.ontimemobile.newfcheckproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi0hN1Oz5iYtnZYrndc0cjnsiV20GRE_U',
    appId: '1:787602166813:ios:f8334a1cb63d9e649c22f4',
    messagingSenderId: '787602166813',
    projectId: 'dtchecker-6e966',
    storageBucket: 'dtchecker-6e966.appspot.com',
    androidClientId: '787602166813-07oq9t6hst61v426gdorak2hao2976gm.apps.googleusercontent.com',
    iosClientId: '787602166813-raoj9gpt4tp6lgf6a10kijo53dh9hjk3.apps.googleusercontent.com',
    iosBundleId: 'com.ontimemobile.newfcheckproject',
  );
}
*/
